import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { Box, Container, Icon, Link } from "@interchain-ui/react";
import { Drawer, Footer, Header } from ".";

import logo from "../../images/cosmology-logo.svg";

export function Layout({ children }: { children: React.ReactNode }) {
  const [show, setShow] = useState(false);

  return (
    <Container maxWidth="64rem" attributes={{ py: "$10" }}>
      <Head>
        <title>Create Cosmos App</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header onMenuButtonClick={() => setShow(true)} />
      <Box minHeight="78vh">
        {children}
      </Box>
      <Footer />
      <Drawer show={show} onClose={() => setShow(false)}>
        <DrawContent onClose={() => setShow(false)} />
      </Drawer>
    </Container>
  );
}

function DrawContent({
  onClose = () => {},
}) {
  return (
    <>
      <Box
        p="$9"
        display="flex"
        alignItems="center"
        borderBottomWidth="1px"
        borderBottomColor="$gray100"
        borderBottomStyle="solid"
      >
        <Link href="/">
          <Image src={logo} alt="Cosmology" width={35} />
        </Link>
        <Box display="flex" flex="1" justifyContent="end">
          <Box attributes={{ onClick: onClose }}>
            <Icon
              name="close"
              size="$5xl"
              color="$blackAlpha600"
            />
          </Box>
        </Box>
      </Box>
      <Box px="$9">
        <Link
          href="/components"
          attributes={{
            my: "$8",
            display: "block",
            fontSize: "$lg",
            fontWeight: "$medium",
            textDecoration: "none",
          }}
        >
          Components
        </Link>
      </Box>
    </>
  );
}
