/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Sg721Updatable.types";
import * as _1 from "./Sg721Updatable.client";
import * as _2 from "./Sg721Updatable.message-composer";
import * as _3 from "./Sg721Updatable.provider";
import * as _4 from "./Whitelist.types";
import * as _5 from "./Whitelist.client";
import * as _6 from "./Whitelist.message-composer";
import * as _7 from "./Whitelist.provider";
import * as _8 from "./Marketplace.types";
import * as _9 from "./Marketplace.client";
import * as _10 from "./Marketplace.message-composer";
import * as _11 from "./Marketplace.provider";
export namespace contracts {
  export const Sg721Updatable = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
  export const Whitelist = { ..._4,
    ..._5,
    ..._6,
    ..._7
  };
  export const Marketplace = { ..._8,
    ..._9,
    ..._10,
    ..._11
  };
}