import Head from 'next/head';
import { Toaster, Container } from '@interchain-ui/react';
import { Header } from './Header';
import { Footer } from './Footer';

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <Container maxWidth="64rem" attributes={{ py: '$14' }}>
      <Head>
        <title>Interchain-Kit Demo</title>
        <meta name="description" content="Generated by Interchain" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Toaster position={"top-right"} closeButton={true} />
      <Footer />
    </Container>
  );
};