import Head from 'next/head';
import { Box, useColorModeValue } from '@interchain-ui/react';
import { Header } from './Header';
import { Sidebar } from './Sidebar';

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <Box
      maxWidth="1440px"
      width="$full"
      minHeight="100vh"
      mx="$auto"
      display="flex"
      backgroundColor={useColorModeValue('$white', '$background')}
    >
      <Head>
        <title>Create Cosmos App</title>
        <meta name="description" content="Generated by create cosmos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <Box p="30px" width="$full">
        <Header />
        {children}
      </Box>
    </Box>
  );
}
