/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./HackCw20.types";
import * as _1 from "./HackCw20.client";
export namespace contracts {
  export const HackCw20 = { ..._0,
    ..._1
  };
}