name: Build Next.js examples
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0

      - name: Build asset-list
        working-directory: ./examples/asset-list
        run: yarn install && yarn build

      - name: Build authz
        working-directory: ./examples/authz
        run: yarn install && yarn build

      - name: Build vote-proposal
        working-directory: ./examples/vote-proposal
        run: yarn install && yarn build

      - name: Build ibc-transfer
        working-directory: ./examples/ibc-transfer
        run: yarn install && yarn build

      - name: Build swap-tokens
        working-directory: ./examples/swap-tokens
        run: yarn install && yarn build

      - name: Build provide-liquidity
        working-directory: ./examples/provide-liquidity
        run: yarn install && yarn build

      - name: Build nft
        working-directory: ./examples/nft
        run: yarn install && yarn build

      - name: Build connect-chain
        working-directory: ./examples/connect-chain
        run: yarn install && yarn build

      - name: Build connect-multi-chain
        working-directory: ./examples/connect-multi-chain
        run: yarn install && yarn build

      - name: Build website
        working-directory: ./examples/website
        run: yarn install && yarn build
