name: Build Next.js examples

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          [
            asset-list,
            authz,
            vote-proposal,
            ibc-transfer,
            swap-tokens,
            provide-liquidity,
            nft,
            connect-chain,
            connect-multi-chain,
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Yarn
        uses: threeal/setup-yarn-action@v2.0.0

      - name: Build asset-list
        working-directory: ./examples/${{ matrix.example }}
        run: yarn install && yarn build
