name: Build Next.js Examples

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  find-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.set-packages.outputs.packages }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find Next.js packages
        id: find-packages
        run: |
          packages=$(ls -d examples/* | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "packages=$packages" >> $GITHUB_ENV
          echo "::set-output name=packages::$packages"
        shell: bash

  build:
    needs: find-packages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJson(needs.find-packages.outputs.packages) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure this matches your Node.js version

      - name: Install Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.0.0 --activate

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js project
        working-directory: ${{ matrix.package }}
        run: yarn build
