name: Run Tests

on:
  workflow_dispatch:
  #push:

  pull_request:
    types: [opened, reopened]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - name: deps
        run: yarn
      - name: bootstrap
        run: yarn bootstrap
      - name: build
        run: yarn build
      - name: react
        run: cd ./packages/react && yarn test
